// #include<iostream>
// using namespace std;
// int main(){
//     int arr[5];
//     cout<<"Enter elements of an array:";
//     for (int i = 0; i <= 4; i++)
    
//     {
//         cin>>arr[i];
//     }
//     for (int i = 0; i <= 4; i++)
//     {
//         cout<<arr[i]*2<<" ";
//     }
    
// }
 

//  easy peasy one if we have values
// it will return reverse of their values
#include<iostream>
using namespace std;
int main(){
    int arr[5]={34,76,54,65,43};
    for (int i = 4; i >=0; i--)
    {
        cout<<arr[i]<<" ";
    }
    
}